image: python:3

stages:
  - test

unit_test:
  stage: test
  script:
    - pip install -r requirements.txt
    - nosetests -v

style_check:
  stage: test
  script:
    - pip install flake8
    - flake8 --exclude=.direnv
