---
topology: milk.graphml
scheduler: picosim.scheduler.FCFSScheduler
host_selector: picosim.host_selector.LinearHostSelector
process_mapper: picosim.process_mapper.LinearProcessMapper
router: picosim.router.DmodKRouter

jobs:
  - submit_at: 0.0
    duration: 100.0
    trace: data/cg-c-128.tar.gz
