version: 2
jobs:
   build:
     docker:
       - image: circleci/python:3.6
     steps:
       - checkout
       - restore_cache:
           key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
       - run:
           command: |
             python3 -m venv venv
             . venv/bin/activate
             pip install -r requirements.txt
             pip install nose flake8
       - save_cache:
           key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
           paths:
             - venv
       - run:
           command: |
             . venv/bin/activate
             nosetests -v
       - run:
           command: |
             . venv/bin/activate
             flake8 --exclude=.direnv
